version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    # For development, you can mount the source code as a volume
    # volumes:
    #   - .:/app
    #   - /app/node_modules
    #   - /app/.next
